"use client"

import * as React from "react"
import {
  Globe,
  Zap,
  Check,
  CircleDot,
  Loader2,
  Database,
  FileSearch,
  ShieldCheck,
  ExternalLink,
} from "lucide-react"
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { StatusPill } from "@/components/ui/status-pill"
import { Expandable } from "@/components/ui/expandable"
import type { EffortOption, EffortLevel, ExaRun } from "@/lib/types"

const EFFORTS: EffortOption[] = [
  { value: "low", label: "Quick Draft", cost: "~$0.025", description: "Prototype, small datasets" },
  { value: "medium", label: "Standard", cost: "~$0.10", description: "Most production use cases" },
  { value: "high", label: "Deep Research", cost: "~$0.50", description: "Large, richly enriched" },
  { value: "xhigh", label: "Exhaustive", cost: "~$1.00", description: "Enterprise-grade research" },
]

const STAGES = ["Queued", "Running", "Enriching rows", "Validating schema", "Complete"]

const PREVIEW_ROWS = [
  { company: "Northwind SaaS", arr: "4.2M", emp: 180, nps: 41, tickets: 312, churned: false },
  { company: "Lumen Analytics", arr: "1.1M", emp: 64, nps: 28, tickets: 540, churned: true },
  { company: "Cedar Cloud", arr: "8.9M", emp: 420, nps: 53, tickets: 211, churned: false },
  { company: "Pivot Metrics", arr: "2.4M", emp: 96, nps: 19, tickets: 690, churned: true },
  { company: "Atlas Stack", arr: "6.0M", emp: 250, nps: 47, tickets: 180, churned: false },
]

const DEFAULT_EXA_RUN: ExaRun = {
  id: "exa_run_demo",
  datasetId: "saas_churn_v2",
  query:
    "Build a labelled churn dataset for B2B SaaS companies, 50-500 employees, with ARR, NPS, support ticket volume, and churn label.",
  efforts: EFFORTS,
  selectedEffort: "medium",
  status: "complete",
  stages: STAGES,
  activeStage: 4,
  stats: { rows: "180", features: "12", qualityScore: "92", runCost: "$0.10" },
  previewRows: PREVIEW_ROWS,
  provenance: [
    { field: "arr_usd", src: "crunchbase.com/northwind-saas" },
    { field: "nps_score", src: "g2.com/products/northwind/reviews" },
    { field: "support_tickets", src: "trustpilot.com/review/northwind" },
  ],
}

export function ExaBuilderCard({ run = DEFAULT_EXA_RUN }: { run?: ExaRun }) {
  const [effort, setEffort] = React.useState<EffortLevel>(run.selectedEffort)
  const [phase, setPhase] = React.useState<"config" | "running" | "complete">(
    run.status === "waiting-approval" ? "config" : run.status,
  )
  const [activeStage, setActiveStage] = React.useState(run.activeStage)

  const selectedEffort = run.efforts.find((e) => e.value === effort) || run.efforts[0]

  const status = phase === "config" ? "waiting-approval" : phase === "running" ? "running" : "complete"

  return (
    <div className="w-full overflow-hidden rounded-xl border border-border bg-surface shadow-sm">
      <header className="flex items-start justify-between gap-3 border-b border-border px-4 py-3 sm:px-5">
        <div className="flex items-start gap-3">
          <span className="mt-0.5 flex h-8 w-8 items-center justify-center rounded-lg bg-info-soft text-primary">
            <Globe className="h-4.5 w-4.5" aria-hidden="true" />
          </span>
          <div>
            <h3 className="text-[15px] font-semibold text-foreground">Exa Web Dataset Builder</h3>
            <p className="mt-0.5 text-xs text-muted-foreground">Generated by Data Agent using Exa Agent API</p>
          </div>
        </div>
        <StatusPill status={status} />
      </header>

      <div className="px-4 py-4 sm:px-5">
        {/* Query */}
        <label className="text-xs font-medium text-muted-foreground" htmlFor="exa-query">
          Dataset request
        </label>
        <div className="mt-1.5 rounded-lg border border-border bg-surface-muted/60 px-3 py-2.5 text-sm text-foreground">
          {run.query}
        </div>

        {/* Effort selector */}
        <div className="mt-4">
          <div className="flex items-center justify-between">
            <span className="text-xs font-medium text-muted-foreground">Research effort</span>
            <span className="text-xs text-muted-foreground">
              Est. cost <strong className="text-foreground">{selectedEffort.cost}</strong>
            </span>
          </div>
          <div role="radiogroup" aria-label="Effort level" className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">
            {run.efforts.map((e) => {
              const active = effort === e.value
              return (
                <button
                  key={e.value}
                  role="radio"
                  aria-checked={active}
                  onClick={() => setEffort(e.value)}
                  className={cn(
                    "flex flex-col rounded-lg border p-2.5 text-left transition-colors",
                    active
                      ? "border-primary bg-info-soft/50 ring-1 ring-primary"
                      : "border-border hover:bg-surface-muted/60",
                  )}
                >
                  <span className="flex items-center gap-1.5 text-[13px] font-semibold text-foreground">
                    {active ? (
                      <Check className="h-3.5 w-3.5 text-primary" aria-hidden="true" />
                    ) : (
                      <Zap className="h-3.5 w-3.5 text-muted-foreground" aria-hidden="true" />
                    )}
                    {e.label}
                  </span>
                  <span className="mt-0.5 text-[11px] font-medium text-primary">{e.cost}</span>
                  <span className="mt-0.5 text-[11px] leading-tight text-muted-foreground">{e.description}</span>
                </button>
              )
            })}
          </div>
        </div>

        {/* Human-in-the-loop gate */}
        {phase === "config" && (
          <div className="mt-4 flex flex-col gap-3 rounded-lg border border-warning/30 bg-warning-soft/60 p-3 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex items-start gap-2.5">
              <ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-warning" aria-hidden="true" />
              <p className="text-[13px] text-foreground">
                This run will spend Exa credits. Estimated cost{" "}
                <strong>{selectedEffort.cost}</strong> at {selectedEffort.label} effort.
              </p>
            </div>
            <div className="flex shrink-0 gap-2">
              <Button variant="outline" size="sm">Cancel</Button>
              <Button size="sm" onClick={() => { setPhase("running"); setActiveStage(1) }}>
                Start Exa Dataset Build
              </Button>
            </div>
          </div>
        )}

        {/* Progress timeline */}
        {phase !== "config" && (
          <ol className="mt-4 flex flex-col gap-0 rounded-lg border border-border bg-surface-muted/40 p-3 sm:flex-row sm:items-center sm:justify-between">
            {run.stages.map((stage, i) => {
              const done = i < activeStage
              const current = i === activeStage && phase === "running"
              const allDone = phase === "complete"
              return (
                <li key={stage} className="flex items-center gap-2 py-1 sm:flex-col sm:gap-1.5 sm:text-center">
                  <span
                    className={cn(
                      "flex h-6 w-6 items-center justify-center rounded-full text-[11px]",
                      done || allDone
                        ? "bg-success text-white"
                        : current
                          ? "bg-info text-white"
                          : "bg-surface-muted text-muted-foreground border border-border",
                    )}
                  >
                    {done || allDone ? (
                      <Check className="h-3.5 w-3.5" aria-hidden="true" />
                    ) : current ? (
                      <Loader2 className="h-3.5 w-3.5 animate-spin" aria-hidden="true" />
                    ) : (
                      <CircleDot className="h-3 w-3" aria-hidden="true" />
                    )}
                  </span>
                  <span
                    className={cn(
                      "text-[11px] font-medium",
                      done || allDone || current ? "text-foreground" : "text-muted-foreground",
                    )}
                  >
                    {stage}
                  </span>
                </li>
              )
            })}
          </ol>
        )}

        {/* Result */}
        {phase === "complete" && (
          <>
            <div className="mt-4 grid grid-cols-2 gap-2.5 sm:grid-cols-4">
              <Stat icon={Database} label="Rows" value={run.stats.rows} />
              <Stat icon={FileSearch} label="Features" value={run.stats.features} />
              <Stat label="Quality score" value={run.stats.qualityScore} tone="success" />
              <Stat label="Run cost" value={run.stats.runCost} />
            </div>

            <div className="mt-4">
              <div className="mb-1.5 flex items-center justify-between">
                <span className="text-xs font-medium text-muted-foreground">
                  Dataset preview (showing {run.previewRows.length} of {run.stats.rows} rows)
                </span>
                <button className="text-xs font-medium text-primary hover:underline">View full dataset</button>
              </div>
              <div className="scroll-thin overflow-x-auto rounded-lg border border-border">
                <table className="w-full min-w-[560px] text-left text-[13px]">
                  <thead className="bg-surface-muted text-[11px] uppercase tracking-wide text-muted-foreground">
                    <tr>
                      <th className="px-3 py-2 font-medium">company</th>
                      <th className="px-3 py-2 font-medium">arr_usd</th>
                      <th className="px-3 py-2 font-medium">employee_count</th>
                      <th className="px-3 py-2 font-medium">nps_score</th>
                      <th className="px-3 py-2 font-medium">support_tickets</th>
                      <th className="px-3 py-2 font-medium">churned</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border font-mono">
                    {run.previewRows.map((r) => (
                      <tr key={r.company} className="hover:bg-surface-muted/50">
                        <td className="px-3 py-2 font-sans font-medium text-foreground">{r.company}</td>
                        <td className="px-3 py-2 text-muted-foreground">{r.arr}</td>
                        <td className="px-3 py-2 text-muted-foreground">{r.emp}</td>
                        <td className="px-3 py-2 text-muted-foreground">{r.nps}</td>
                        <td className="px-3 py-2 text-muted-foreground">{r.tickets}</td>
                        <td className="px-3 py-2">
                          <span
                            className={cn(
                              "rounded px-1.5 py-0.5 text-[11px] font-sans font-medium",
                              r.churned ? "bg-error-soft text-error" : "bg-success-soft text-success",
                            )}
                          >
                            {String(r.churned)}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            <Expandable label="Provenance — field-level web sources (output.grounding)" className="mt-4">
              <ul className="space-y-2 text-[13px]">
                {run.provenance.map((p) => (
                  <li key={p.field} className="flex items-center justify-between gap-3 rounded-md bg-surface-muted/60 px-3 py-2">
                    <span className="font-mono text-xs text-foreground">{p.field}</span>
                    <a
                      href="#"
                      className="flex items-center gap-1 text-xs text-primary hover:underline"
                      aria-label={`Source for ${p.field}`}
                    >
                      {p.src}
                      <ExternalLink className="h-3 w-3" aria-hidden="true" />
                    </a>
                  </li>
                ))}
              </ul>
            </Expandable>

            <div className="mt-4 flex flex-wrap items-center gap-2">
              <Button>Use this dataset</Button>
              <Button variant="outline">Refine / Get more rows</Button>
            </div>
          </>
        )}
      </div>
    </div>
  )
}

function Stat({
  icon: Icon,
  label,
  value,
  tone = "default",
}: {
  icon?: React.ElementType
  label: string
  value: string
  tone?: "default" | "success"
}) {
  return (
    <div className="rounded-lg border border-border bg-surface-muted/60 px-3 py-2.5">
      <div className="flex items-center gap-1.5 text-xs font-medium text-muted-foreground">
        {Icon && <Icon className="h-3.5 w-3.5" aria-hidden="true" />}
        {label}
      </div>
      <div className={cn("mt-1 text-lg font-semibold tabular-nums", tone === "success" ? "text-success" : "text-foreground")}>
        {value}
      </div>
    </div>
  )
}
