import { Sparkles, TrendingUp, Target, ArrowRight } from "lucide-react"
import { AgentCard, MetricBlock } from "./agent-card"
import { Button } from "@/components/ui/button"
import { Expandable } from "@/components/ui/expandable"
import type { StrategySummary } from "@/lib/types"

const DEFAULT_STRATEGY: StrategySummary = {
  summary:
    "Based on your retention KPI, I recommend a churn prediction model as the primary use case, with two supporting opportunities. Here is the projected impact map.",
  metrics: [
    { label: "Use cases mapped", value: "3", tone: "primary" },
    { label: "Projected 12-mo ROI", value: "$1.4M", tone: "success", hint: "Blended estimate" },
    { label: "Feasibility", value: "High", tone: "success", hint: "Data available" },
  ],
  useCases: [
  { name: "Churn Prediction", type: "Classification", confidence: "High", roi: "+$1.2M ARR retained" },
  { name: "Expansion Propensity", type: "Regression", confidence: "Medium", roi: "+18% upsell rate" },
  { name: "Support Deflection RAG", type: "Retrieval", confidence: "High", roi: "-32% ticket volume" },
  ],
}

export function StrategyCard({ strategy = DEFAULT_STRATEGY }: { strategy?: StrategySummary }) {
  return (
    <AgentCard
      title="AI Strategy Generated"
      status="complete"
      icon={Sparkles}
      source="Generated by Strategy Agent using LLM + Exa enrichment"
    >
      <p className="text-sm leading-relaxed text-foreground">
        {strategy.summary}
      </p>

      <div className="mt-4 grid grid-cols-2 gap-2.5 sm:grid-cols-3">
        {strategy.metrics.map((metric) => (
          <MetricBlock
            key={metric.label}
            label={metric.label}
            value={metric.value}
            tone={metric.tone}
            hint={metric.hint}
          />
        ))}
      </div>

      <div className="mt-4 overflow-hidden rounded-lg border border-border">
        <table className="w-full text-left text-sm">
          <thead className="bg-surface-muted text-[11px] uppercase tracking-wide text-muted-foreground">
            <tr>
              <th className="px-3 py-2 font-medium">Use Case</th>
              <th className="px-3 py-2 font-medium">Task Type</th>
              <th className="hidden px-3 py-2 font-medium sm:table-cell">Projected ROI</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border">
            {strategy.useCases.map((uc) => (
              <tr key={uc.name} className="hover:bg-surface-muted/50">
                <td className="px-3 py-2.5">
                  <div className="font-medium text-foreground">{uc.name}</div>
                  <div className="text-[11px] text-muted-foreground sm:hidden">{uc.roi}</div>
                </td>
                <td className="px-3 py-2.5">
                  <span className="rounded-md bg-info-soft px-2 py-0.5 text-[11px] font-medium text-primary">
                    {uc.type}
                  </span>
                </td>
                <td className="hidden px-3 py-2.5 text-muted-foreground sm:table-cell">{uc.roi}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <Expandable label="Why the agent recommended this" className="mt-4">
        <div className="space-y-2 text-[13px] leading-relaxed text-muted-foreground">
          <p className="flex gap-2">
            <Target className="mt-0.5 h-4 w-4 shrink-0 text-primary" aria-hidden="true" />
            <span>
              <strong className="text-foreground">What:</strong> A supervised classification model to flag
              accounts likely to churn within 90 days.
            </span>
          </p>
          <p className="flex gap-2">
            <TrendingUp className="mt-0.5 h-4 w-4 shrink-0 text-primary" aria-hidden="true" />
            <span>
              <strong className="text-foreground">Why:</strong> Your KPI is retention improvement and the
              available data contains labelled churn outcomes with 12 usable predictive features.
            </span>
          </p>
        </div>
      </Expandable>

      <div className="mt-4 flex flex-wrap items-center gap-2">
        <Button>
          Confirm strategy
          <ArrowRight className="h-4 w-4" aria-hidden="true" />
        </Button>
        <Button variant="outline">Adjust use cases</Button>
      </div>
    </AgentCard>
  )
}
